
package com.project.weatherreport.domain.forecastModel
import com.google.gson.annotations.SerializedName
data class Hour(
    @SerializedName("air_quality") val air_quality: AirQualityX,
    @SerializedName("chance_of_rain") val chance_of_rain: Int,
    @SerializedName("chance_of_snow") val chance_of_snow: Int,
    @SerializedName("cloud") val cloud: Int,
    @SerializedName("condition") val condition: Condition,
    @SerializedName("dewpoint_c") val dewpoint_c: Double,
    @SerializedName("dewpoint_f") val dewpoint_f: Double,
    @SerializedName("feelslike_c") val feelslike_c: Double,
    @SerializedName("feelslike_f") val feelslike_f: Double,
    @SerializedName("gust_kph") val gust_kph: Double,
    @SerializedName("gust_mph") val gust_mph: Double,
    @SerializedName("heatindex_c") val heatindex_c: Double,
    @SerializedName("heatindex_f") val heatindex_f: Double,
    @SerializedName("humidity") val humidity: Int,
    @SerializedName("is_day") val is_day: Int,
    @SerializedName("precip_in") val precip_in: Double,
    @SerializedName("precip_mm") val precip_mm: Double,
    @SerializedName("pressure_in") val pressure_in: Double,
    @SerializedName("pressure_mb") val pressure_mb: Double,
    @SerializedName("temp_c") val temp_c: Double,
    @SerializedName("temp_f") val temp_f: Double,
    @SerializedName("time") val time: String,
    @SerializedName("time_epoch") val time_epoch: Int,
    @SerializedName("uv") val uv: Double,
    @SerializedName("vis_km") val vis_km: Double,
    @SerializedName("vis_miles") val vis_miles: Double,
    @SerializedName("will_it_rain") val will_it_rain: Int,
    @SerializedName("will_it_snow") val will_it_snow: Int,
    @SerializedName("wind_degree") val wind_degree: Int,
    @SerializedName("wind_dir") val wind_dir: String,
    @SerializedName("wind_kph") val wind_kph: Double,
    @SerializedName("wind_mph") val wind_mph: Double,
    @SerializedName("windchill_c") val windchill_c: Double,
    @SerializedName("windchill_f") val windchill_f: Double
)